### ISSUE TITLE
Microphone not working on Snap version

### ISSUE THREAD

**Issue by crystaldaking** [canonical/steam-snap#316]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you checked the wiki for solutions?

- [X] I have searched the wiki

### Is this a Steam Snap-specific issue?

- [X] This is a Steam Snap-specific issue

### Current Behavior

Open Settings -> Voice -> Start microphone test

No voice here and u cant manage input devices (only "default" section)

### Expected Behavior

Open Settings -> Voice -> Start microphone test

You can hear ur voice and u cant manage input devices 

### Environment

```yaml
crystal@crystal-ubuntu-pc:~$ snap run steam.report
Traceback (most recent call last):
  File "/snap/steam/165/bin/nvidia32", line 3, in <module>
    import gi
  File "/snap/steam/165/usr/lib/python3/dist-packages/gi/__init__.py", line 40, in <module>
    from . import _gi
ImportError: libgirepository-1.0.so.1: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/snap/steam/165/bin/steamreport", line 9, in <module>
    import gi
  File "/snap/steam/165/usr/lib/python3/dist-packages/gi/__init__.py", line 40, in <module>
    from . import _gi
ImportError: libgirepository-1.0.so.1: cannot open shared object file: No such file or directory
crystal@crystal-ubuntu-pc:~$ 

Computer Information:
Manufacturer: Unknown
Model: Unknown
Form Factor: Desktop
No Touch Input Detected
Processor Information:
CPU Vendor: AuthenticAMD
CPU Brand: AMD Ryzen 9 7900X 12-Core Processor
CPU Family: 0x19
CPU Model: 0x61
CPU Stepping: 0x2
CPU Type: 0x0
Speed: 5651 MHz
24 logical processors
12 physical processors
Hyper-threading: Supported
FCMOV: Supported
SSE2: Supported
SSE3: Supported
SSSE3: Supported
SSE4a: Supported
SSE41: Supported
SSE42: Supported
AES: Supported
AVX: Supported
AVX2: Supported
AVX512F: Supported
AVX512PF: Unsupported
AVX512ER: Unsupported
AVX512CD: Supported
AVX512VNNI: Supported
SHA: Supported
CMPXCHG16B: Supported
LAHF/SAHF: Supported
PrefetchW: Unsupported
Operating System Version:
Ubuntu Core 22 (64 bit)
Kernel Name: Linux
Kernel Version: 6.5.0-7-generic
X Server Vendor: The X.Org Foundation
X Server Release: 12101007
X Window Manager: GNOME Shell
Steam Runtime Version: steam-runtime_0.20230801.56012
Video Card:
Driver: Mesa llvmpipe (LLVM 15.0.7, 256 bits)
Driver Version: 4.5 (Compatibility Profile) Mesa 23.2.1 - kisak-mesa PPA
OpenGL Version: 4.5
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 165 Hz
VendorID: 0x10de
DeviceID: 0x2782
Revision Not Detected
Number of Monitors: 1
Number of Video Cards Not Detected
Primary Display Resolution: 1920 x 1080
Desktop Resolution: 1920 x 1080
Primary Display Size: 20.75" x 11.65" (23.78" diag), 52.7cm x 29.6cm (60.4cm diag)
Primary Bus: PCI Express 16x
Primary VRAM: 7168 MB
Supported MSAA Modes: 2x 4x 8x 16x
Sound card:
Audio device: %1$s
Memory:
RAM: 31219 Mb
VR Hardware:
VR Headset: None detected
Miscellaneous:
UI Language: English
LANG: en_US.UTF-8
Total Hard Disk Space Available: 250898 MB
Largest Free Hard Disk Block: 158606 MB
Storage:
Number of SSDs: 0
Number of HDDs: 0
Number of removable drives: 0


crystal@crystal-ubuntu-pc:~$ nvidia-smi
Sun Oct  8 23:15:57 2023       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 4070 Ti     Off | 00000000:01:00.0  On |                  N/A |
|  0%   52C    P5              23W / 285W |   1451MiB / 12282MiB |     25%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A      3392      G   /usr/lib/xorg/Xorg                          400MiB |
|    0   N/A  N/A      3581      G   /usr/bin/gnome-shell                         54MiB |
|    0   N/A  N/A      4370      G   ...64222371,6034121623372459468,262144       77MiB |
|    0   N/A  N/A      5039      G   ...sktop/5133/usr/bin/telegram-desktop       61MiB |
|    0   N/A  N/A     63894      G   ...re/Steam/ubuntu12_64/steamwebhelper        9MiB |
|    0   N/A  N/A     63988      G   ...eam/logs/cef_log.txt --shared-files       31MiB |
|    0   N/A  N/A     68321      G   ...,WinRetrieveSuggestionsOnlyOnDemand       36MiB |
|    0   N/A  N/A     74490    C+G   ..._32/../ubuntu12_64/fossilize_replay      117MiB |
|    0   N/A  N/A     74571    C+G   ..._32/../ubuntu12_64/fossilize_replay      111MiB |
|    0   N/A  N/A     74604    C+G   ..._32/../ubuntu12_64/fossilize_replay      103MiB |
|    0   N/A  N/A     74719    C+G   ..._32/../ubuntu12_64/fossilize_replay      103MiB |
|    0   N/A  N/A     74784    C+G   ..._32/../ubuntu12_64/fossilize_replay      103MiB |
|    0   N/A  N/A     74963    C+G   ..._32/../ubuntu12_64/fossilize_replay      103MiB |
|    0   N/A  N/A     75172      G   /usr/bin/nautilus                            15MiB |
|    0   N/A  N/A     76317      G   /snap/snap-store/1046/bin/snap-store         55MiB |
+---------------------------------------------------------------------------------------+
crystal@crystal-ubuntu-pc:~$
```

### gaming-graphics-core22 version

kisak-fresh (default)

**Comment by crystaldaking** [comment]
![image](https://github.com/canonical/steam-snap/assets/25440397/01e97f34-26b1-4532-bd65-9ef9e87d5d8b)

**Comment by Rovano01** [comment]
OMG. Enabled audio record fixed it. Thanks for a tip.
It's hidden all the way down in Discover. I have NEVER seen this setting. I just discovered it now. :-)

**Comment by Nedimko123** [comment]
> ![image](https://github.com/canonical/steam-snap/assets/25440397/01e97f34-26b1-4532-bd65-9ef9e87d5d8b)

Thanks so much, had to enable Record Audio permission

**Comment by ashuntu** [comment]
`audio-record` now should auto-connect for new Steam snap installations.

https://forum.snapcraft.io/t/auto-connect-audio-record-for-steam/52936
