### ISSUE TITLE
Steam segfault

### ISSUE THREAD

**Issue by pmeyerson** [canonical/steam-snap#334]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you checked the wiki for solutions?

- [X] I have searched the wiki

### Is this a Steam Snap-specific issue?

- [X] This is a Steam Snap-specific issue

### Current Behavior

snap steam fails with a segfault on steam.sh  after citing the below error.
I have removed and purged and reinstalled.
Ubuntu 22.04 and radeon x6600.

the deb package works fine, and glxgears deb package works fine although steam glxgears fails.

first running glxgears deb is fine, below when i try to run via snap:

```
❯ glxgears
Running synchronized to the vertical refresh.  The framerate should be
approximately the same as the monitor refresh rate.
396 frames in 5.0 seconds = 79.084 FPS
X connection to :1 broken (explicit kill or server shutdown).
❯ snap run steam.glxgears
Traceback (most recent call last):
  File "/snap/steam/165/bin/nvidia32", line 3, in <module>
    import gi
ModuleNotFoundError: No module named 'gi'
/usr/share/libdrm/amdgpu.ids: No such file or directory
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: radeonsi
/usr/share/libdrm/amdgpu.ids: No such file or directory
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: radeonsi
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
Error: glXCreateContext failed
 ~                              
```

### Expected Behavior

UI should appear when running steam.

### Steps To Reproduce

1. click on desktop icon for snap steam
2. steam begins to update itself
3. crash and fail

### Environment

```yaml
❯ snap run steam.report
Traceback (most recent call last):
  File "/snap/steam/165/bin/nvidia32", line 3, in <module>
    import gi
  File "/snap/steam/165/usr/lib/python3/dist-packages/gi/__init__.py", line 40, in <module>
    from . import _gi
ImportError: libgirepository-1.0.so.1: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/snap/steam/165/bin/steamreport", line 9, in <module>
    import gi
  File "/snap/steam/165/usr/lib/python3/dist-packages/gi/__init__.py", line 40, in <module>
    from . import _gi
ImportError: libgirepository-1.0.so.1: cannot open shared object file: No such file or directory
 ~ 
```

**Comment by ashuntu** [comment]
Does this persist after restarting your computer?

**Comment by pmeyerson** [comment]
Yes it does, thanks.

**Comment by pmeyerson** [comment]
Sure, sorry I didnt include this earlier.

❯ /snap/bin/steam
Testing for explicit PulseAudio choice...
...and PulseAudio has been explicitly chosen, so using it.
steam.sh[16598]: Running Steam on ubuntu 22.04 64-bit
steam.sh[16598]: STEAM_RUNTIME is enabled automatically
setup.sh[16718]: Steam runtime environment up-to-date!
steam.sh[16598]: Steam client's requirements are satisfied
[2023-11-14 14:38:37] Startup - updater built Oct 31 2023 02:08:17
[2023-11-14 14:38:37] Startup - Steam Client launched with: '/home/rhekis/snap/steam/common/.local/share/Steam/ubuntu12_32/steam' '-no-cef-sandbox'
11/14 14:38:37 Init: Installing breakpad exception handler for appid(steam)/version(1698777785)/tid(16766)
/usr/share/libdrm/amdgpu.ids: No such file or directory
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: radeonsi
/usr/share/libdrm/amdgpu.ids: No such file or directory
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: radeonsi
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
SteamUpdateUI: An X Error occurred
X Error:  BadValue
Request Major code 152 (GLX)
Request Minor code 3
Value 0x0
Error Serial #53
xerror_handler: X failed, continuing
Looks like steam didn't shutdown cleanly, scheduling immediate update check
[2023-11-14 14:38:37] Loading cached metrics from disk (/home/rhekis/snap/steam/common/.local/share/Steam/package/steam_client_metrics.bin)
[2023-11-14 14:38:37] Failed to load cached hosts file (File 'update_hosts_cached.vdf' not found), using defaults
[2023-11-14 14:38:37] Using the following download hosts for Public, Realm steamglobal
[2023-11-14 14:38:37] 1. https://cdn.steamstatic.com, /client/, Realm 'steamglobal', weight was 1, source = 'baked in'
[2023-11-14 14:38:37] Checking for update on startup
[2023-11-14 14:38:37] Checking for available updates...
[2023-11-14 14:38:37] Downloading manifest: https://cdn.steamstatic.com/client/steam_client_ubuntu12
[2023-11-14 14:38:37] Manifest download: send request
[2023-11-14 14:38:37] Manifest download: waiting for download to finish
[2023-11-14 14:38:38] Manifest download: finished
[2023-11-14 14:38:38] Download skipped: /client/steam_client_ubuntu12 version 1698777785, installed version 1698777785, existing pending version 0
[2023-11-14 14:38:38] Nothing to do
[2023-11-14 14:38:38] Verifying installation...
[2023-11-14 14:38:38] Performing checksum verification of executable files
[2023-11-14 14:38:39] Verification complete

Steam logging initialized: directory: /home/rhekis/snap/steam/common/.local/share/Steam/logs


(process:16766): GLib-GIO-CRITICAL **: g_settings_schema_source_lookup: assertion `source != NULL' failed
XRRGetOutputInfo Workaround: initialized with override: 0 real: 0xf67ad370
XRRGetCrtcInfo Workaround: initialized with override: 0 real: 0xf67abcc0
/usr/share/libdrm/amdgpu.ids: No such file or directory
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: radeonsi
/usr/share/libdrm/amdgpu.ids: No such file or directory
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: radeonsi
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
11/14 14:38:39 Failed writing minidump, nothing to upload.
/home/rhekis/snap/steam/common/.local/share/Steam/steam.sh: line 798: 16766 Segmentation fault      (core dumped) "$STEAMROOT/$STEAMEXEPATH" "$@"
 ~    
 
 steam boostrap log:
 [2023-11-14 14:38:37] Startup - updater built Oct 31 2023 02:08:17
[2023-11-14 14:38:37] Startup - Steam Client launched with: '/home/rhekis/snap/steam/common/.local/share/Steam/ubuntu12_32/steam' '-no-cef-sandbox'
[2023-11-14 14:38:37] Loading cached metrics from disk (/home/rhekis/snap/steam/common/.local/share/Steam/package/steam_client_metrics.bin)
[2023-11-14 14:38:37] Failed to load cached hosts file (File 'update_hosts_cached.vdf' not found), using defaults
[2023-11-14 14:38:37] Using the following download hosts for Public, Realm steamglobal
[2023-11-14 14:38:37] 1. https://cdn.steamstatic.com, /client/, Realm 'steamglobal', weight was 1, source = 'baked in'
[2023-11-14 14:38:37] Checking for update on startup
[2023-11-14 14:38:37] Checking for available updates...
[2023-11-14 14:38:37] Downloading manifest: https://cdn.steamstatic.com/client/steam_client_ubuntu12
[2023-11-14 14:38:37] Manifest download: send request
[2023-11-14 14:38:37] Manifest download: waiting for download to finish
[2023-11-14 14:38:38] Manifest download: finished
[2023-11-14 14:38:38] Download skipped: /client/steam_client_ubuntu12 version 1698777785, installed version 1698777785, existing pending version 0
[2023-11-14 14:38:38] Nothing to do
[2023-11-14 14:38:38] Verifying installation...
[2023-11-14 14:38:38] Performing checksum ve

**Comment by pmeyerson** [comment]
LMK if there is anything else that would be helpful, thanks for taking a look!

**Comment by spillner** [comment]
FYSA this is not a Snap- or Ubuntu-specific issue; it appears to be an upstream issue with some version combinations of Mesa and its supporting libraries.  I ran into the same issue on a Slackware installation (also running a Radeon RX 6600), as did many others.  The problems started after I installed Mesa 23.3.0 (which was pushed to Slackware64-current around 3 December), and persisted until I upgraded to 23.3.1.  Other users reported success downgrading to older versions of Mesa and/or the llvm and spirv-llvm-translator packages.  cf. https://www.linuxquestions.org/questions/slackware-14/steam-in-6-6-7-a-4175731988/ and https://github.com/ValveSoftware/steam-for-linux/issues/10263 

Hope this helps!

**Comment by jssotomdz** [comment]
I saw this same issue with another snap https://github.com/jssotomdz/jmp-snap/issues/4 And apparently an update to latest mesa fixes it. This user reported using mesa from the [mesarc ppa](https://launchpad.net/~ernstp/+archive/ubuntu/mesarc) which is publishing Mesa 23.3.2. So maybe an update `sudo snap refresh --channel=oibaf-latest/stable` could be fixing this? Because reverting to an older version isn't ideal and oibaf ships Mesa 24

**Comment by pmeyerson** [comment]
thanks everyone!

And FYI i still get moduleNotFoundError but it is not fatal:

`❯ steam.glxgears
find: ‘/home/rhekis/snap/steam/common/.local/share/applications’: No such file or directory
find: ‘/home/rhekis/snap/steam/common/.local/share/icons/hicolor’: No such file or directory
Traceback (most recent call last):
  File "/snap/steam/171/bin/nvidia32", line 3, in <module>
    import gi
ModuleNotFoundError: No module named 'gi'
/usr/share/libdrm/amdgpu.ids: No such file or directory
Running synchronized to the vertical refresh.  The framerate should be
approximately the same as the monitor refresh rate.
` but the glxgears window pops fine.
