### ISSUE TITLE
Missing packages in the steam snap cause failure with nvidia bit userspace

### ISSUE THREAD

**Issue by zyga** [canonical/steam-snap#396]
### Ensure there isn't an existing issue for this and check the wiki

- [X] This issue is not a duplicate and I have checked the wiki.

### Current Behavior

```
zyga@falka:~$ GBM_BACKEND=nvidia-drm __GLX_VENDOR_LIBRARY_NAME=nvidia snap run steam
Testing for explicit PulseAudio choice...
...and PulseAudio has been explicitly chosen, so using it.
INFO: filtering /usr/share/ubuntu-xorg out of XDG_DATA_DIRS because it is unreachable
INFO: filtering /usr/share/gnome out of XDG_DATA_DIRS because it is unreachable
INFO: filtering /etc/xdg/xdg-ubuntu-xorg out of XDG_CONFIG_DIRS because it is unreachable
Traceback (most recent call last):
  File "/snap/steam/191/bin/nvidia32", line 3, in <module>
    import gi
  File "/snap/steam/191/usr/lib/python3/dist-packages/gi/__init__.py", line 40, in <module>
    from . import _gi
ImportError: libgirepository-1.0.so.1: cannot open shared object file: No such file or directory
steam.sh[92562]: Running Steam on ubuntu 24.10 64-bit
steam.sh[92562]: STEAM_RUNTIME is enabled automatically
setup.sh[92637]: Steam runtime environment up-to-date!
```

### Expected Behavior

The gir import should not fail

### Steps To Reproduce

```sh
sudo snap install steam -r 191
GBM_BACKEND=nvidia-drm __GLX_VENDOR_LIBRARY_NAME=nvidia snap run steam
```

### Environment

```yaml
The report script doesn't work:

INFO: filtering /usr/share/ubuntu-xorg out of XDG_DATA_DIRS because it is unreachable
INFO: filtering /usr/share/gnome out of XDG_DATA_DIRS because it is unreachable
INFO: filtering /usr/local/share/ out of XDG_DATA_DIRS because it is unreachable
INFO: filtering /usr/share/ out of XDG_DATA_DIRS because it is unreachable
INFO: filtering /var/lib/snapd/desktop out of XDG_DATA_DIRS because it is unreachable
INFO: filtering /etc/xdg/xdg-ubuntu-xorg out of XDG_CONFIG_DIRS because it is unreachable
INFO: filtering /etc/xdg out of XDG_CONFIG_DIRS because it is unreachable
Traceback (most recent call last):
  File "/snap/steam/191/bin/nvidia32", line 3, in <module>
    import gi
  File "/snap/steam/191/usr/lib/python3/dist-packages/gi/__init__.py", line 40, in <module>
    from . import _gi
ImportError: libgirepository-1.0.so.1: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/snap/steam/191/bin/steamreport", line 9, in <module>
    import gi
  File "/snap/steam/191/usr/lib/python3/dist-packages/gi/__init__.py", line 40, in <module>
    from . import _gi
ImportError: libgirepository-1.0.so.1: cannot open shared object file: No such file or directory
steam-runtime-launcher-service: no process found
```
```


### gaming-graphics-core22 version

kisak-fresh (default)

### Anything else?


_No response_

**Comment by zyga** [comment]
This is likely a duplicate of https://github.com/canonical/steam-snap/issues/379

**Comment by ashuntu** [comment]
Does trying what is described in this comment resolve the issue? https://github.com/canonical/steam-snap/issues/379#issuecomment-2079506227

**Comment by zyga** [comment]
> Does trying what is described in this comment resolve the issue? [#379 (comment)](https://github.com/canonical/steam-snap/issues/379#issuecomment-2079506227)

Nope
